### ISSUE TITLE
Create simple server with a single claim endpoint

### ISSUE THREAD

**Issue by arschles** [deis/k8s-claimer#1]
This issue covers creating a set of endpoints related to leasing and releasing a cluster for use. It does not cover any backend implementation or authentication. The goal of this issue is _only_ to agree on the API.
Here's my proposal of what the endpoint can look like:
# Leasing a Cluster
### Request

``` console
POST /lease

{
  "max_time": "30m"
}
```
### Successful Response

``` console
201 CREATED

{
  "kubeconfig": "<entire_kubeconfig_here>",
  "ip": "IP address here",
  "token": "<claim_token_here>"
}
```
### Failure Response

In the case that there are no clusters available:

``` console
409 CONFLICT
```
### Notes
- The claim token is a UUID used by clients to assert their ownership of the cluster. In the future, it may be used to determine whether they own a cluster, to release the cluster, and more
- The cluster will automatically be released back into the pool (and the aforementioned UUID invalidated) after the `max_time` (in the request body) has elapsed.
# Releasing a Cluster
### Request

``` console
DELETE /lease/{token}
```

Token is the UUID that the client was assigned when leasing the cluster.
### Successful Response

``` console
200 OK
```
### Error Response

``` console
401 NOT AUTHORIZED
```

If the token does not correspond to a valid, leased cluster.

**Comment by jackfrancis** [comment]
What are some practical scenarios in which a cluster lease request would fail? A `404` response doesn't smell right. A `400` might be better for requests that are definitively judged to be malformed input, and something `500`-ish would be better for accepted requests that bail somewhere in the business logic execution flow.

**Comment by arschles** [comment]
@jackfrancis Here's my thinking:
- A 404 would be valuable if there's no cluster available
- There will, in the future, be logic to create a new cluster when there are none left (probably with a high watermark)
- I'd like that logic to not be automatic in this endpoint, however
- Rather, I'd like the caller to use this `404` to determine that it should call another endpoint to create and lease the new cluster (atomically)

**Comment by jchauncey** [comment]
is `token` a uuid of the cluster?

**Comment by arschles** [comment]
yep. I'll add that to notes

**Comment by jackfrancis** [comment]
@arschles got it. If there were a way to more explicitly express this in the API, it could be a win for the humans using it. E.g.,

`POST /lease` / `POST /reservation` etc.

Just picking a nit, not a deal breaker!

**Comment by arschles** [comment]
Good call. I like `/lease`, so I'll change to that.

**Comment by slack** [comment]
Seems like a good start! Possibly `409 Conflict` for a POST without adequate capacity. Otherwise, a client who gets a bad route would happily go creating clusters on the pretense of a 404 (perhaps).

Also makes me wonder if the client should be requesting new cluster creation, or if pool management should strictly be a backend concern. Not a blocker, can figure that out later!

**Comment by arschles** [comment]
k, `409` sgtm
