### ISSUE TITLE
Implement auth for the lease and release endpoints

### ISSUE THREAD

**Issue by arschles** [deis/k8s-claimer#17]
It can be something simple, but nobody should be able to get a lease or release one if they aren't authenticated and authorized.

**Comment by arschles** [comment]
[this article](https://auth0.com/blog/2016/04/13/authentication-in-golang/) may help

**Comment by bacongobbler** [comment]
Are we looking for something simple like plain HTTP auth or JWT?

**Comment by arschles** [comment]
Yup, and I was thinking that JWT would fit well here. Thoughts?

**Comment by bacongobbler** [comment]
:shipit:

**Comment by vdice** [comment]
We'll probably want to get this done sooner rather than later... Noticed after a fresh deis install on the `k8s-claimer-e2e` [champagne cluster](https://console.cloud.google.com/compute/quotas?project=deis-champagne) was already receiving requests from _interested third parties_:

```
[20/Apr/2016:22:06:08 +0000] - 10.36.2.1 - - - 404 - "GET http://g.wujieliulan.com/mnews.htm HTTP/1.1" - 747 - "-" - "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)" - "_" - - - g.wujieliulan.com - - - 0.000
2016/04/20 22:06:31 [crit] 28#0: *990 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init) while SSL handshaking, client: 10.36.2.1, server: 0.0.0.0:6443
```

(etc.)

**Comment by arschles** [comment]
Punting to beta4
