### ISSUE TITLE
Discuss the cluster recycling strategy

### ISSUE THREAD

**Issue by arschles** [deis/k8s-claimer#20]
This issue is a continuation of https://github.com/deis/k8s-claimer/pull/16#discussion_r58802030.

A cluster recycling strategy is defined by how often clusters whose leases are expired get reused. We've considered the following cluster recycling strategies:
1. Look for the most stale expired lease in the annotations. If none is found, find a free GKE cluster (special case of 2)
2. Look for any expired lease in the annotations. If none is found, find a free GKE cluster
3. Find a free GKE cluster, then look for an expired lease in the annotations
4. Find a free GKE cluster, then look for the most stale expired lease in the annotations (special case of 3)

Currently, we do (3) (see [the leasing algorithm document](https://github.com/deis/k8s-claimer/blob/master/doc/architecture.md#leasing-algorithm)). Implementing (4) may more evenly recycle clusters, but either 3 or 4 are more fair than 1 or 2 assuming that clusters are properly released more often than having their leases expire.

My guess is that we'll need to test out various strategies in production. This issue is for discussion of the aforementioned strategies, or proposing new ones.

**Comment by jackfrancis** [comment]
should "how often cluster whose leases are expired get reused" be "how _quickly_ clusters whose leases are expired get reused"? The word "often" suggests periodicity, and a cluster's lease will only expire once. (unless I'm misunderstanding something)

**Comment by arschles** [comment]
@jackfrancis it'd be how quickly & how often. Say a bad actor keeps leasing for 1 second - that cluster _could_ very often (and hence, very quickly) be recycled both in (2) and (3)

**Comment by arschles** [comment]
In fact, it could also very often/quickly be recycled in (1) and (4) if all other clusters are leased

**Comment by jchauncey** [comment]
closing this as the latest prs address some of these issues
