### ISSUE TITLE
make task for testing bintray deploy/publish

### ISSUE THREAD

**Issue by vdice** [deis/k8s-claimer#58]
Would be nice to add a `make test-bintray-deploy` that would, minimally, vet the `bintray-ci.json` produced by current `make prep-bintray-json` via a `--dry-run`, and maybe even consider a non-dry-run version that would actually attempt deploy (before waiting for master Travis job to inform on whether stuff is all good.)  Somethin' like:

```
test-bintray-deploy: dist prep-bintray-json
  dpl --provider=bintray --user="${USER}" --key="${BINTRAY_API_KEY}" --file=_scripts/ci/bintray-ci.json  --dry-run
```

Obviously, this depends on the [dpl](https://github.com/travis-ci/dpl) gem, so we'd either have to also add a `make` task to install the gem first or execute the command via a Docker image prepped w/ ruby and this gem -- or both.

**Comment by jchauncey** [comment]
Wish we could put this in a more generic place. Maybe in workflow-cli? Since we publish to bintray there as well?

**Comment by Joshua-Anderson** [comment]
We no longer use bintray, so I'm closing this.
