### ISSUE TITLE
Add better error handling

### ISSUE THREAD

**Issue by jchauncey** [deis/k8s-claimer#63]
```
$ curl -X POST -H "Authorization: 123"  http://my-k8s-claimer.com/lease
error decoding JSON (EOF)
```

**Comment by arschles** [comment]
A nice improvement here would be to have the CLI read and output the response body on failures

**Comment by mboersma** [comment]
@jchauncey do we still emit useless error messages here?

**Comment by jchauncey** [comment]
Hrm we do get some weird errors but its better. I'll close this for now
