### ISSUE TITLE
Feature request: Expire credentials when lease is deleted or expires

### ISSUE THREAD

**Issue by krancour** [deis/k8s-claimer#95]
This doesn't currently happen. But shouldn't it? As it stands now, you can lease a cluster and then squat on it indefinitely-- even while a new lessee uses it.

This could _probably_ be done by provisioning a new service account for the cluster in question when it is leased. These would be the credentials returned to lessee. That same service account could be de-provisioned when the lease is either deleted or expires.

**Comment by arschles** [comment]
Agree, I think this is technically possible. However, we currently operate on a trusted lessee model. Do we have reason to believe that a lessee would be malicious and hijack a cluster like this?

**Comment by krancour** [comment]
@arschles, it doesn't even need to be malicious for this to go sideways. Suppose I lease a cluster for ten minutes and then quite innocently kick off something within that cluster that takes much longer to complete than expected... or blocks indefinitely even.

And I'm realizing now that may also be impetus to build cleanup logic into k8s-claimer... maybe logic that deletes all namespaces that aren't `kube-system` before returning the cluster to the pool. (I did manage to lease a very dirty cluster during my demo yesterday.)

Last, re: the notion of "trusted lessees," since this is open source, I don't want to make assumptions that anyone else hypothetically using k8s-claimer can trust all lesees. Can we even trust all of ours? Leased clusters are used to test PRs... malicious code in a PR or an accidental indefinite blocking or infinite loop could wreak havoc with a leased cluster that someone else might soon hold the lease on.

**Comment by arschles** [comment]
@krancour good point. I'm good with leaving this open. also note that the cleanup logic was added to k8s-claimer (https://github.com/deis/k8s-claimer/pull/68). I believe it was working at some point, but I don't know what happened to it since.
